name: 'Uptime'
description: 'Checks if a resource is available and if it has changed since the last check'
author: 'Justin Kenyon'
branding:
  icon: 'archive'
  color: 'gray-dark'
inputs:
  url:
    description: 'publicly accessible URL (ex. `https://github.com/kenyonj/actions-uptime.git`)'
    required: true
  frequency_in_minutes:
    description: 'An integer value to indicate how many minutes we should wait before the next uptime check (ex. `300` for checking every 5 hours)
    required: true
    default: 1440
  yaml_output:
    description: 'A boolean value to indicate whether or not this action will write to a YAML file to keep track of how long the resource has been available'
    required: true
    default: true
  pushover_user_key:
    description: 'A string value for your pushover user key, use secrets to protect this information (ex. `${{ secrets.PUSHOVER_USER_KEY }}`'
    required: false
  pushover_token:
    description: 'A string value for your pushover token, use secrets to protect this information (ex. `${{ secrets.PUSHOVER_TOKEN }}`'
    required: false
outputs:
  change_detected:
    description: 'A boolean value to indicate that a change was detected on the resource'
    value: ${{ steps.cache.outputs.cache-hit == 'true' }}
  resource_is_available:
    description: 'A boolean value to indicate that the resource is up and responding to GET requests'
    value: ${{ steps.fetch.conclusion == 'success' }}
  notification_sent:
    description: 'A boolean value to indicate that a notification was sent to the desired services'
runs:
  using: "composite"
  steps:
    - name: Fetch data
      id: fetch
      run: curl "${{ inputs.url }}" -o data.json

    - name: Fetch Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: data.json
        key: ${{ hashFiles('data.json') }}

    - name: Pushover Notification
      id: pushover-notification
      run: curl -s --form-string "token=${{ inputs.pushover_token }}" --form-string "user=${{ inputs.pushover_user_key }}" --form-string "message=uptime-action has run" https://api.pushover.net/1/messages.json
      if: ${{ inputs.pushover_token && inputs.pushover_user_key }}
